[server]
maxUploadSize = 50
enableXsrfProtection = false
enableCORS = true
runOnSave = false
headless = true

[browser]
gatherUsageStats = false
serverAddress = "phosconsultoria.com.br"

[theme]
base = "dark"
primaryColor = "#2c6b96"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1c23"
textColor = "#ece8e6"
font = "sans serif"
